import { Inter } from "next/font/google";
import Script from 'next/script'

import "./globals.css";
import '../../public/leaflet.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CitiLens",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <>
      <html lang="en">
        <body className={inter.className}>{children}
          <Script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" strategy="beforeInteractive" />
          <Script src="/leaflet-heat.js" strategy="beforeInteractive" />
        </body>
      </html >
    </>
  );
}
